### ISSUE TITLE
does not take the path to the Ffmpeg file

### ISSUE THREAD

**Issue by alexriosrr** [spz2k9/iocage-plugin-jellyfin#11]
Hello friend, I use a freebsd and truenas operating system, which after the 10.18.13 update does not want to take the folder or path to the ffmpeg therefore it does not allow many files to be played, I have already tried uninstalling and installing again by changing the json, now that 13.2 release is incompatible, and I went to 13.1 again to be able to install, I don't know what else to do, honestly, I appreciate your help.

Im from colombia, thanks.

**Comment by spz2k9** [comment]
- You use freebsd or TrueNas ? Which version ?
- After the 10.18.13 ?
Normally the actual plugin is compatible to 13.2 on TrueNas 13.0-U6.1... i'll try to test it later.

**Comment by spz2k9** [comment]
oh i see the plugin version is 10.18.13... but it should display 10.18.13_1 on TrueNas 13.0-U6.1 make sure the OS is upgraded to the last one.

Oh and if u were on 10.18.13 it might not be possible to upgrade do 10.18.13_1 because ffmpeg changes from 4.3 to 6.0 and they're not that much compatible. If you can try creating a new jail with the latest version.

**Comment by alexriosrr** [comment]
Yes friend, the truenas is in the latest version, but it also gives problems when installing the 13.2 release, therefore the jail was left in 13.1, I am trying to reinstall the jellyfin to a version 13.8.10... finally I will update the jail again to see.

I'll tell you later, thanks

**Comment by alexriosrr** [comment]
Amigo yo creo que debe ser un error en parte de IXsystems al actualizar el truenas pero bueno, intente de todo pero no pude arreglar el ffmpeg , esperare para cuando haya una nueva actualizacion, mientras me pasare a Ubuntu, lol , gracias bro.
